In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sentence = [
    'The glass of milk',
    'The glass of juice',
    'The cup of tea',
    'I am a good person',
    'I am a good developer',
    'Understanding the meaning of words',
    'The videos are good'
]
voc_size = 500

#### One_Hot_Encoding

In [3]:
onehot_repr = [one_hot(word, voc_size) for word in sentence]
print(onehot_repr)

[[431, 476, 189, 417], [431, 476, 189, 452], [431, 244, 189, 202], [132, 242, 173, 96, 323], [132, 242, 173, 96, 65], [478, 431, 364, 189, 475], [431, 206, 355, 96]]


#### Word embedding representation

In [4]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

#### Pre-Padding

In [5]:
sentence_length = 8
embedded_docs = pad_sequences(onehot_repr, padding = 'pre', maxlen = sentence_length)
print(embedded_docs)

[[  0   0   0   0 431 476 189 417]
 [  0   0   0   0 431 476 189 452]
 [  0   0   0   0 431 244 189 202]
 [  0   0   0 132 242 173  96 323]
 [  0   0   0 132 242 173  96  65]
 [  0   0   0 478 431 364 189 475]
 [  0   0   0   0 431 206 355  96]]


#### Setting a 10 feature dimension

In [7]:
dim = 10
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sentence_length))
model.compile('adam','rse')
model.predict(embedded_docs)

c:\Users\Amreet\Desktop\NLP\NLP\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step


array([[[-0.01301723, -0.00108662, -0.04132137,  0.02309126,
          0.02578744,  0.04249266, -0.04090729,  0.00450731,
         -0.03793967,  0.03573665],
        [-0.01301723, -0.00108662, -0.04132137,  0.02309126,
          0.02578744,  0.04249266, -0.04090729,  0.00450731,
         -0.03793967,  0.03573665],
        [-0.01301723, -0.00108662, -0.04132137,  0.02309126,
          0.02578744,  0.04249266, -0.04090729,  0.00450731,
         -0.03793967,  0.03573665],
        [-0.01301723, -0.00108662, -0.04132137,  0.02309126,
          0.02578744,  0.04249266, -0.04090729,  0.00450731,
         -0.03793967,  0.03573665],
        [ 0.00205506,  0.00716865, -0.01395572, -0.03380241,
         -0.02619652, -0.03840851,  0.00606748,  0.01569916,
         -0.0491646 ,  0.02691598],
        [-0.03386682, -0.04751248, -0.03497412,  0.01173105,
         -0.02636142, -0.01017267,  0.00980538, -0.01770563,
         -0.04999174, -0.01692646],
        [ 0.00275468, -0.01471126, -0.01514991,  0.0

## Another

In [16]:
from numpy import array
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [17]:
# define documents
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
# define class labels
labels = array([1,1,1,1,1,0,0,0,0,0])

In [18]:
# integer encode the documents
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[48, 11], [22, 11], [17, 5], [38, 11], [47], [19], [21, 5], [4, 22], [21, 11], [25, 3, 11, 23]]


In [19]:
# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(onehot_repr, maxlen=max_length, padding='post')
print(padded_docs)

[[431 476 189 417]
 [431 476 189 452]
 [431 244 189 202]
 [242 173  96 323]
 [242 173  96  65]
 [431 364 189 475]
 [431 206 355  96]]


In [23]:
# define the model
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# summarize the model
# print(model.summary())

# fit the model
model.fit(padded_docs, labels, epochs=50, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 100.000000


For more ref : [How to use word embedding layers](https://machinelearningmastery.com/use-word-embedding-layers-deep-learning-keras/)